workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      java: 21
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor for Android
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor for iOS
        script: npx cap sync ios
      - name: Build iOS App
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            build
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
