workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Capacitor Sync
        script: |
          npx cap sync ios
      - name: Build iOS
        script: |
          # Note: Capacitor 6+ uses Swift Package Manager (SPM) by default, no CocoaPods needed
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            build
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
