workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    scripts:
      - npm install
      - npx cap sync android
      - |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    scripts:
      - npm install
      - npx cap sync ios
      - |
        xcodebuild \
          -project ios/App/App.xcodeproj \
          -scheme App \
          -configuration Debug \
          -sdk iphonesimulator \
          -destination 'generic/platform=iOS Simulator' \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          build
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
